"""Builds the four accreditation badges as single-colour, transparent assets so the header and footer can tint them
to the background (CSS mask + currentColor). Run with `npm run badges` (needs Python 3 and Pillow).

Sources:
  REC            official vector logo from rec.uk.com, stored as path data in lib/rec-logo.ts
  Hot 100 2024   Recruiter's 2024 HOT 100 seal, 600 px (white on black), as published by another listed firm
                 (merakitalent.com awards page); fawkesandreece.co.uk only hosts it at 50 px
  FAST 50        fawkesandreece.co.uk/wp-content/uploads/image-1-1.png (38x50, the only copy available)
  FT 1000        fawkesandreece.co.uk/wp-content/uploads/image-2.png (82x50; the seal is licensed by Statista
                 behind its award portal, so there is no public high-resolution file)
"""
import io
import re
import urllib.request

import numpy as np
from PIL import Image

UA = {"User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) Chrome/126"}


def fetch(url):
    return urllib.request.urlopen(urllib.request.Request(url, headers=UA), timeout=30).read()


def mask(img, alpha, scale, out):
    """Write a white image whose alpha is the given 0..1 array, trimmed to its ink and upscaled `scale` times."""
    alpha = np.clip(alpha, 0, 1)
    ys, xs = np.where(alpha > 0.04)
    alpha = alpha[ys.min():ys.max() + 1, xs.min():xs.max() + 1]
    a = Image.fromarray((alpha * 255).astype(np.uint8), "L")
    if scale != 1:
        a = a.resize((a.width * scale, a.height * scale), Image.LANCZOS)
    rgba = Image.new("RGBA", a.size, (255, 255, 255, 0))
    rgba.putalpha(a)
    rgba.save(out, optimize=True)
    print(out, rgba.size)


def lum(img):
    return np.asarray(img.convert("L"), dtype=float) / 255


# Hot 100 2024: white seal on black, so ink is brightness.
hot = Image.open(io.BytesIO(fetch("https://merakitalent.com/assets/Uploads/hot-100__ScaleMaxWidthWzcxMF0.png")))
mask(hot, (lum(hot) - 0.12) / 0.8, 1, "public/badges/hot100-2024.png")

# FAST 50: a dark tile with the words knocked out, so ink is darkness. The grey "50" stays partly solid, as printed.
fast = Image.open(io.BytesIO(fetch("https://fawkesandreece.co.uk/wp-content/uploads/image-1-1.png")))
mask(fast, (0.92 - lum(fast)) / 0.8, 4, "public/badges/fast50.png")

# FT 1000: dark marks on a light grey card (#ececec), so ink is darkness measured from the card.
ft = Image.open(io.BytesIO(fetch("https://fawkesandreece.co.uk/wp-content/uploads/image-2.png")))
mask(ft, (0.9 - lum(ft)) / 0.6, 4, "public/badges/ft1000.png")

# REC: keep the official paths; the letters and the dotted mark become two tones of one colour.
svg = fetch("https://www.rec.uk.com/application/themes/rawnet/app/images/interface/logo.svg").decode()
view = re.search(r'viewBox="([^"]+)"', svg).group(1)
letters = re.search(r'<path d="([^"]+)" style="fill:#fff"', svg).group(1)
dots = re.findall(r'<circle class="st1" cx="([\d.]+)" cy="([\d.]+)" r="([\d.]+)"', svg)
dot_paths = re.findall(r'<path class="st1" d="([^"]+)"', svg)
with open("lib/rec-logo.ts", "w") as f:
    f.write("// Official REC logo (rec.uk.com logo.svg), generated by scripts/badges.py. Do not edit by hand.\n")
    f.write(f'export const recViewBox = "{view}";\n')
    f.write(f'export const recLetters = "{letters}";\n')
    f.write(f"export const recDots = {[{'cx': float(c[0]), 'cy': float(c[1]), 'r': float(c[2])} for c in dots]!r};\n".replace("'", '"'))
    f.write(f"export const recDotPaths = {dot_paths!r};\n".replace("'", '"'))
print("lib/rec-logo.ts", len(dots), "dots", len(dot_paths), "dot paths")
