// Rebuilds the Fawkes & Reece logo as vectors. The company only publishes a 280 px GIF (Fawkes-Reece-Logo-280.gif)
// and a 64 px symbol PNG, so every coordinate below was measured from those rasters, in the GIF's 280 px space:
//   FAWKES  blue  x 25–255, cap 167.5–206.5
//   REECE   green x 73–255, cap 216.5–256
//   plus    x 25–57, y 220–252; bars 15/64 of the mark (symbol PNG: bars at 25–40 of 64)
// The wordmark is set in Gotham in the original; Montserrat SemiBold (OFL) is the closest open match. Each line is
// scaled to the measured cap height, then tracked so its ends land on the measured x positions.
// Writes lib/logo.ts (per-letter paths for the preloader) and the SVG files in public/brand.
import { readFile, writeFile, mkdir } from "node:fs/promises";
import opentype from "opentype.js";

const BLUE = "#00A2E5", GREEN = "#99CA3C", OVERLAP = "#00AA4F", BLACK = "#000000";
// Weight 600 overlaps the GIF best (pixel IoU 0.72; 500 gave 0.63, 700 gave 0.71).
const WEIGHT = process.env.LOGO_WEIGHT ?? "600";
const buf = await readFile(`node_modules/@fontsource/montserrat/files/montserrat-latin-${WEIGHT}-normal.woff`);
const font = opentype.parse(buf.buffer.slice(buf.byteOffset, buf.byteOffset + buf.byteLength));
const capH = font.tables.os2.sCapHeight;
const r = (n) => Math.round(n * 100) / 100;

function setLine(word, left, right, capTop, capBottom) {
  const size = (capBottom - capTop) / (capH / font.unitsPerEm);
  const glyphs = font.stringToGlyphs(word);
  const scale = size / font.unitsPerEm;
  // Ink extents of each glyph at this size (advance-independent), so tracking is measured ink to ink.
  const inks = glyphs.map((g) => { const b = g.getBoundingBox(); return { x1: b.x1 * scale, x2: b.x2 * scale }; });
  const inkWidth = inks.reduce((sum, ink, i) => sum + (ink.x2 - ink.x1) + (i ? 0 : 0), 0);
  const naturalGaps = inks.slice(1).map((ink, i) => (glyphs[i].advanceWidth * scale - inks[i].x2) + ink.x1);
  const extra = ((right - left) - inkWidth - naturalGaps.reduce((a, b) => a + b, 0)) / (glyphs.length - 1);
  let pen = left;
  return glyphs.map((g, i) => {
    const x = pen - inks[i].x1;
    const d = g.getPath(x, capBottom, size).toPathData(2);
    pen += (inks[i].x2 - inks[i].x1) + (i < glyphs.length - 1 ? naturalGaps[i] + extra : 0);
    return { char: word[i], d };
  });
}

const fawkes = setLine("FAWKES", 25, 255, 167.5, 206.5);
const reece = setLine("REECE", 73, 255, 216.5, 256);

// The mark: blue upright, green crossbar, and the darker green square where they overlap.
const m = { x: 25, y: 220, size: 32 };
const bar = m.size * 15 / 64, off = m.size * 25 / 64;
const mark = {
  vertical: { x: r(m.x + off), y: m.y, w: r(bar), h: m.size },
  horizontal: { x: m.x, y: r(m.y + off), w: m.size, h: r(bar) },
  overlap: { x: r(m.x + off), y: r(m.y + off), w: r(bar), h: r(bar) },
};

// Tight bounds of the lockup (tile excluded) for the header and footer.
const box = { x: 25, y: 167.5, w: 230, h: 88.5 };

const rect = (b, fill) => `<rect x="${b.x}" y="${b.y}" width="${b.w}" height="${b.h}" fill="${fill}"/>`;
const letters = (line, fill) => `<path fill="${fill}" d="${line.map((l) => l.d).join(" ")}"/>`;
const svg = ({ tile, mono }) => {
  const [vb, bg] = tile ? ["0 0 280 280", `<rect width="280" height="280" fill="${BLACK}"/>`] : [`${box.x} ${box.y} ${box.w} ${box.h}`, ""];
  const blue = mono ?? BLUE, green = mono ?? GREEN, overlap = mono ?? OVERLAP;
  return `<svg xmlns="http://www.w3.org/2000/svg" viewBox="${vb}" role="img" aria-label="Fawkes &amp; Reece">${bg}${letters(fawkes, blue)}${rect(mark.vertical, blue)}${rect(mark.horizontal, green)}${rect(mark.overlap, overlap)}${letters(reece, green)}</svg>\n`;
};

await mkdir("public/brand", { recursive: true });
await writeFile("public/brand/logo.svg", svg({}));
await writeFile("public/brand/logo-tile.svg", svg({ tile: true }));
await writeFile("public/brand/logo-white.svg", svg({ mono: "#FFFFFF" }));
await writeFile("public/brand/logo-black.svg", svg({ mono: BLACK }));
await writeFile("public/brand/symbol.svg", `<svg xmlns="http://www.w3.org/2000/svg" viewBox="0 0 64 64"><rect x="25" y="0" width="15" height="64" fill="${BLUE}"/><rect x="0" y="25" width="64" height="15" fill="${GREEN}"/><rect x="25" y="25" width="15" height="15" fill="${OVERLAP}"/></svg>\n`);

const ts = `// Generated by scripts/logo.mjs from measurements of the official 280 px logo. Do not edit by hand.
// Coordinates are in the original logo's 280 px space; \`box\` is the lockup without its black tile.
export const logoBox = ${JSON.stringify(box)} as const;
export const logoMark = ${JSON.stringify(mark)} as const;
export const logoFawkes = ${JSON.stringify(fawkes)} as const;
export const logoReece = ${JSON.stringify(reece)} as const;
`;
await writeFile("lib/logo.ts", ts);
console.log("logo written", fawkes.length + reece.length, "letters");
